# Generated by Django 3.0.7 on 2022-01-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='miles',
            new_name='Kilometers',
        ),
    ]
